#!/bin/sh

set -e

PREREQ=""

prereqs()
{
    echo "$PREREQ"
}

case "$1" in
prereqs)
    prereqs
    exit 0
    ;;
esac

. /usr/share/initramfs-tools/hook-functions

mkdir -p "${DESTDIR}/sbin"

copy_exec /usr/local/andsec/bin/andsec-disks-crypt-init-ui /sbin/andsec-disks-crypt-init-ui
